# Versions are provided at: https://docs.nvidia.com/networking/display/kubernetes<driver-version>/platform-support.html
apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: nic-cluster-policy
spec:
  # This is needed so that you don't schedule pods on the non-infiniband machines.
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        # This node label is added by NFD.
        - key: feature.node.kubernetes.io/pci-15b3.present
          operator: In
          values:
          - "true"

  ofedDriver:
    repository: nvcr.io/nvidia/mellanox
    image: doca-driver
    # Latest tag: https://catalog.ngc.nvidia.com/orgs/nvidia/teams/mellanox/containers/doca-driver/tags
    # When this is deployed a suffix is added in the format "-<os><os version>-<cpu arch>" for e.g.: "-ubuntu22.04-amd64".
    version: doca3.2.0-25.10-1.2.8.0-2

    env:
    # TODO: Temporary fix to avoid race condition where the kernel module fails to load.
    # Refer: https://github.com/Mellanox/doca-driver-build/issues/52
    - name: OFED_BLACKLIST_MODULES_FILE
      value: "/host/etc/modprobe.d/blacklist-ofed-modules.conf"

    forcePrecompiled: false
    upgradePolicy:
      autoUpgrade: true
      drain:
        deleteEmptyDir: true
        enable: true
        force: true
        timeoutSeconds: 300
      maxParallelUpgrades: 1
    startupProbe:
      initialDelaySeconds: 10
      periodSeconds: 20
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 30
  docaTelemetryService:
    repository: nvcr.io/nvidia/doca
    image: doca_telemetry
    version: 1.22.5-doca3.1.0-host
