# Versions are provided at: https://docs.nvidia.com/networking/display/kubernetes<driver-version>/platform-support.html
apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
  name: nic-cluster-policy
spec:
  sriovDevicePlugin:
    repository: nvcr.io/nvidia/mellanox
    image: sriov-network-device-plugin
    version: network-operator-v25.10.0
    # Selector explaination:
    # - vendors: ["15b3"] - Vendor ID for Mellanox devices
    # - linkTypes: ["infiniband"] - Link type for Infiniband devices
    # - isRdma: true - Mounts the RDMA device to the container's /dev/infiniband
    config: |
      {
        "resourceList": [
          {
            "resourcePrefix": "rdma",
            "resourceName": "ib",
            "selectors": {
              "vendors": ["15b3"],
              "linkTypes": ["infiniband"],
              "isRdma": true
            }
          }
        ]
      }
